### ISSUE TITLE
Problem with pasting multiline code snippets

### ISSUE THREAD

**Issue by andy-zero** [jonsequitur/dotnet-repl#15]
I'm not sure having plain Enter key as default execute is good idea?
When you try to paste a multiline code snippet, repl executes after every line, which obviously makes pasting quite impossible.

If the execute key was Shift + Enter and newline was plain Enter (the opposite of what it is now) then you would be able to paste multiline and then execute.

Is there some other way of pasting that I'm not aware? Am I making a fool of myself?

BTW. I love this tool - great work! I was trying to bind some multiline array with data to quickly transform the data but failed at pasting the text in.
![image](https://user-images.githubusercontent.com/57894394/122235170-62fbbe80-ceb5-11eb-9aba-23483a1cbd8f.png)

**Comment by jonsequitur** [comment]
@patriksvensson What do you think?

**Comment by patriksvensson** [comment]
@jonsequitur I will try to fix this tonight in Radline. Will submit a PR for you

**Comment by jonsequitur** [comment]
This is fixed in version 0.1.30.
