### ISSUE TITLE
Exiting the tool is not documented

### ISSUE THREAD

**Issue by simonvane** [jonsequitur/dotnet-repl#16]
(Great tool by the way)

Once I've finished using the tool, I'm not sure how to exit it and carry on with my normal terminal session.

![image](https://user-images.githubusercontent.com/1423185/122234856-1dd78c80-ceb5-11eb-951a-e656619968de.png)

I've tried things like typing exit, q etc.

Thanks.

**Comment by jonsequitur** [comment]
`Ctrl-C` should do the trick. I'll add it to the help.

**Comment by simonvane** [comment]
Thank you.
