### ISSUE TITLE
Stuck in infinite loop

### ISSUE THREAD

**Issue by kevingosse** [jonsequitur/dotnet-repl#18]
Consider this sequence:

```
C# > interface ITest { public void Test(); }

C# > typeof(ITest).GetMethods()
```

At this point, dotnet-repl seems to go into some kind of infinite loop and becomes unresponsive while using large amounts of CPU.

**Comment by kevingosse** [comment]
I'm not familiar with this code yet, but it looks like it's trying to render a graph of objects that has a loop in it.

**Comment by jonsequitur** [comment]
This is the same problem as #8. The recursion depth check is not in place like it is in the default .NET Interactive formatters.
