### ISSUE TITLE
Can't change kernel to pwsh after moving from csharp to fsharp

### ISSUE THREAD

**Issue by unuunc** [jonsequitur/dotnet-repl#21]
![image](https://user-images.githubusercontent.com/5947364/122597998-d524fc80-d089-11eb-8ead-6b704b74a1c0.png)

**Comment by unuunc** [comment]
1. Go to default Csharp kernel.
2. Change to go to Fsharp kernel
3. Try to change to Pwsh kernel it does not work 
4. you can go to csharp kernel and can go to pwsh kernel thou

**Comment by jonsequitur** [comment]
It looks like it did change to `pwsh`. What were you expecting to see?

**Comment by unuunc** [comment]
I was expecting change in kernel from fsharp kernel as well , it is working from fsharp kernel.

**Comment by jonsequitur** [comment]
Oh, I see. I followed your repro steps and it worked fine for me so I missed the obvious in your screen shot. 

I'm using 0.1.30 where it seems like this works as you expect. What version are you using?

**Comment by unuunc** [comment]
This was issue in 0.1.11 , sorry , should have mentioned it , but it is working fine in 0.1.35, so closing it. thanks
