### ISSUE TITLE
Tab on an empty line results in  System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by DeonHeyns** [jonsequitur/dotnet-repl#23]
To repro:
type dotnet-repl and hit enter
at the prompt hit tab

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/857353/122617331-71d3a400-d062-11eb-8bc8-20a3763e135e.png">

**Comment by patriksvensson** [comment]
@DeonHeyns What version of dotnet-repl are you running? I think this was recently fixed (but I guess @jonsequitur would know for sure)

**Comment by jonsequitur** [comment]
This is fixed in version 0.1.30 which was just published.
