### ISSUE TITLE
PowerShell profile does not run when exiting dotnet-repl with Ctrl+C

### ISSUE THREAD

**Issue by simonvane** [jonsequitur/dotnet-repl#25]
This image shows my PowerShell profile running on startup of my terminal. In this example, my profile just has `Write-Host "Running profile..."` in it.

When I click Ctrl+C to exit dotnet-repl my profile doesn't run so my terminal is not ready to use.

![image](https://user-images.githubusercontent.com/1423185/122632804-04109200-d0cd-11eb-9b20-2901f7e79616.png)

(My actual use case is using Powerline in Windows Terminal. See https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup. When I click Ctrl+C, my prompt is not set up.)

**Comment by jonsequitur** [comment]
What version are you using?

This seems to work for me on 0.1.30; 
![image](https://user-images.githubusercontent.com/547415/122650056-991f8500-d0e5-11eb-8b21-b6b9116c1b2f.png)

**Comment by simonvane** [comment]
Thank you. I updated to 0.1.35 and it's working now.
