### ISSUE TITLE
Output is incorrect in bash

### ISSUE THREAD

**Issue by ironsm4sh** [jonsequitur/dotnet-repl#57]
When using powershell, the tool looks fine. but when using it from bash (such as git-bash or MSYS2) none of the dynamic outputs align correctly.
![image](https://user-images.githubusercontent.com/23172578/177288489-a7eaa891-84be-48be-a49d-0a4298f5aeae.png)

Would it be possible to correct this or/and add a launch flag which cleans the output so that it is also usable in a CI/CD environment (no ANSI console)?

An example:
```
$> dotnet repl --notebook mynotebook.dib --exit-after-run --basic-output
Running notebook: mynotebook.dib
Installing Packages
| LibGit2Sharp, 0.27.0-preview-0182
| Microsoft.Build, 16.11.0

Your notebook output here...

$>
```

**Comment by patriksvensson** [comment]
@ironsm4sh Are you by any chance using "Ambiguous-width character" in your terminal? What terminal are you using?

**Comment by ironsm4sh** [comment]
Hey, sorry for taking such a long time. I do not have access to the computer I used at the time anymore, and I can not reproduce it using my current system. I was using `ConEmu` at the time.

That said, I do think there is value in an explicit mode with a minimal CLI output, for CI/CD environments. However, I do not have a usecase for that anymore, so I am closing this issue.

Thanks for your replies and attention.
