### ISSUE TITLE
Trying to run the REPL gives a "missing dotnet SDK" message

### ISSUE THREAD

**Issue by OmanF** [jonsequitur/dotnet-repl#68]
Hi.
I'm not sure if this message belongs here, or if it was asked and answered before, but hopefully, you can help me figure it out.

I installed the tool as per the instructions on the README of the repo and started it per instructions only to get the error shown in the attached screenshot (which also shows I *do* have an active SDK, and according to issue #44 support for .Net6.0 was added, so I don't get it).

If there's any more information I need to provide, let me know.

Thanks in advance.

![2022-08-28_10-35](https://user-images.githubusercontent.com/7848797/187063608-e2a38f1a-8b44-4823-abda-c620bc95042f.png)

**Comment by jonsequitur** [comment]
This looks like an SDK issue and shouldn't be specific to `dotnet-repl`.

Are other global tool installations working for you? 

This looks like it might be relevant: https://stackoverflow.com/questions/71251998/the-required-library-libhostfxr-so-could-not-be-found-netcore-linux

**Comment by OmanF** [comment]
Weird... when installing using `-g` flag this keeps happening.
But when I uninstalled it globally and installed it locally - works!
And yeah, other builds work fine.

I encountered this issue before and then I "solved" it by upgrading my .Net SDK and runtime.
Guess I'll do that again.
Thanks.
