### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by minecraftchest1** [jonsequitur/dotnet-repl#9]
I would like to give thanks and appreciation for this project. I have thought about doing something like this but didn't have an idea of how to do it. I have only done a quick test of the app, but it seems to be working well.

**Comment by jonsequitur** [comment]
Thanks!

The real magic of course is in [.NET Interactive](https://github.com/dotnet/interactive) and [Spectre.Console](https://github.com/spectreconsole/spectre.console).
