### ISSUE TITLE
Describe with #!set should detect the variable name instead of the prompt text

### ISSUE THREAD

**Issue by marckruzik** [jonsequitur/dotnet-repl#90]
I am using #!set to set a variable `my_name` in a notebook.

The notebook code:
```
#!set --name my_name --value @input:"please enter value"
```

The CLI command (working as intended):
```
dotnet repl --run test.dib --exit-after-run --input my_name="hello" --output-path output.ipynb
```

### The bug

When using the describe command `dotnet repl describe test.dib`, it does not detect correctly the variable name. Instead, it detects the prompt text displayed to the user.
Here is a screenshot with the variable name (1) and the name detected by describe (2):
![2023_11_03-15h36m41s-C__Windows_System32_cmd exe](https://github.com/jonsequitur/dotnet-repl/assets/51711029/092e849b-9a75-4ebe-952b-80c0512dc24a)

I think the variable name detected by describe (2) should be "my_name".

I am using dotnet-repl v0.1.205.

**Comment by jonsequitur** [comment]
This is a bug in `Microsoft.DotNet.Interactive.Documents`. I'm closing it here and have opened an issue [here]().

**Comment by jonsequitur** [comment]
Updating to the latest .NET Interactive libraries with the bug fix resolves the problem: 

<img width="393" alt="image" src="https://github.com/jonsequitur/dotnet-repl/assets/547415/76136b00-2815-4cc9-8f53-df1fa7987916">
